import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { theme } from "@/theme/antd";
import { Almarai, Barlow } from "@/utils/customFonts";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Welcome to CEBOT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={theme}>
      <html lang="en">
        <body
          className={`${Barlow.variable} ${Almarai.variable} antialiased max-w-[1440px] mx-auto px-5
          md:px-10 bg-neutrals-black text-neutrals-white relative scroll-smooth overflow-x-hidden`}
        >
          <AntdRegistry>
            <NavBar />
            {children}
            <Footer />
          </AntdRegistry>
        </body>
      </html>
    </ConfigProvider>
  );
}
