import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { Almarai, Barlow } from "@/utils/customFonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Barlow.variable} ${Almarai.variable} antialiased max-w-[1440px] mx-auto px-11 bg-neutrals-black text-neutrals-white relative`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
